name: Build

on:
  push:
    branches:
      - "master"
      - "dev/**"
      - "ga"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Haiku build dependencies
        run: |
          sudo apt install -y git nasm bc autoconf automake texinfo flex bison gawk build-essential unzip wget zip less zlib1g-dev libzstd-dev xorriso libtool python3

      - name: Fetch cached Haiku build
        id: cache
        uses: actions/cache@v3
        with:
          path: 'haiku-build'
          key: 'haiku-build'

      - name: Build Haiku
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          export HAIKU_BUILD_ENVIRONMENT_ROOT=$GITHUB_WORKSPACE/haiku-build
          ./copy_objects.sh

      - name: Install HyClone build dependencies
        run: |
          sudo apt install -y cmake libgmp-dev libmpfr-dev zlib1g-dev

      - name: Build HyClone
        run: |
          export HAIKU_BUILD_ENVIRONMENT_ROOT=$GITHUB_WORKSPACE/haiku-build
          ./copy_objects.sh
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=.
          make install
          cd ..

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hyclone
          path: build
